### PR TITLE
Add a mode flag to bm_drawline() to either set or clear pixels in a l…

### PR DESCRIPTION
**Pull request by tschak909**
…ine. Alter test lib to reflect change. Alter header to reflect change.

### CODE REVIEW

**Comment by tursilion** [comment]
Sorry for the delay getting to this - I don't log into Github proper very often, and the last few months have been crazy. Anyway... please merge latest and resubmit.

**Comment by tschak909** [comment]
Ok, I will soon. am in the middle of a crunch. :)

**Comment by tursilion** [comment]
Ping ;)

**Comment by tursilion** [comment]
hm. It doesn't conflict, so I'm going to go ahead and merge.

**Pull request merged**
